<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevNews.Service.Domain\DevNews.Service.Domain.csproj" />
    <ProjectReference Include="..\DevNews.Services.Application\DevNews.Services.Application.csproj" />
  </ItemGroup>

</Project>
